#!/usr/bin/env bash
echo "downloading new firefox version"
firefox_url="$(curl -Ss https://www.mozilla.org/en-US/firefox/nightly/all/  | grep -Eo '(https).*(os=linux64).*(es-MX)')"
echo "firefox_url is: $firefox_url"
wget -qO - "${firefox_url}" | tar -jxvf - -C /opt/

update-alternatives --install /usr/bin/x-www-browser x-www-browser /opt/firefox/firefox 1000
update-alternatives --install /usr/bin/gnome-www-browser gnome-www-browser /opt/firefox/firefox 1000

